name: dist
on:
  push:
    branches:
    - main
    - "**"
    - release-candidate/**

jobs:
  dist:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Cache Yarn
        uses: actions/cache@v2
        with:
          path: |
            ~/cache/yarn
            ~/cache/cypress
          # Reuses cache from `build` workflow
          key: build-${{ runner.os }}-yarn-v3-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            build-${{ runner.os }}-yarn-v3-
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ./target/*/deps
            ./target/*/build
            ./target/*/.fingerprint
          key: ${{ github.job }}-${{ runner.os }}-rust-v6-${{ hashFiles('Cargo.lock') }}
      - run: ci/dist.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist-${{runner.os}}
          path: |
            dist/*.dmg
            dist/*.AppImage
            dist/*/upstream-seed


  publish-artifacts:
    needs:
      - dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist-Linux
          path: dist
      - uses: actions/download-artifact@v2
        with:
          name: dist-macOS
          path: dist
      - name: publish artifacts by commit
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: dist
          destination: radicle-upstream-build-artifacts/v1/by-commit/${{ github.sha }}
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
      - name: publish main artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: google-github-actions/upload-cloud-storage@v0.4.0
        with:
          path: dist
          destination: radicle-upstream-build-artifacts/v1/main/
          credentials: ${{ secrets.GCP_SECRET_KEY }}
          parent: false
